name: CI Back-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'back-end/**'
  
# Modificar workflow para que o job que compila o projeto do back-end, realiza os testes e cria o arquivo JAR, seja dividido em dois jobs, sendo um para teste e outro para criar o arquivo JAR.
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test
        working-directory: back-end/
        run: mvn --activate-profiles prod test


  package:
    steps:
      - uses: actions/checkout@v3
      - name: Criando arquivo Jar
        working-directory: back-end/
        run: mvn --activate-profiles prod -DskipTests package
